name: Deploy

on:
  workflow_dispatch:
    inputs:
      kafkajs_version:
        description: 'KafkaJS Version'
        required: true

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update KafkaJS
        env:
          KAFKAJS_VERSION: ${{ github.event.inputs.kafkajs_version }}
        run: |
          cd kafkajs
          npm install --save kafkajs@${KAFKAJS_VERSION}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: kafkajs-canary-app
          IMAGE_TAG: '${{ github.event.inputs.kafkajs_version }}-${{ github.sha }}'
        run: |
          cd app  
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit
        env:
          KAFKAJS_VERSION: ${{ github.event.inputs.kafkajs_version }}
        run: |
          git add app/package.json app/package-lock.json
          git commit -m "Update KafkaJS to ${KAFKAJS_VERSION}"
          git push origin master

      - name: Deploy to fargate
        env:
          IMAGE_TAG: '${{ github.event.inputs.kafkajs_version }}-${{ github.sha }}'
        run: |
          cd infrastructure
          npm ci
          (cd src && npm ci)
          npm run deploy -- AppStack --parameters version=${IMAGE_TAG}
